backend:
  name: git-gateway
  branch: master

media_folder: '/static/blog/media'
public_folder: '/blog'

collections:
  - name: 'post'
    label: 'Post'
    folder: 'static/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'date',
          timeFormat: false,
          format: 'DD MM YYYY',
        }
      - { label: 'Snippet', name: 'snippet', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
